### ISSUE TITLE
Stackpath provider - no suitable version installed

### ISSUE THREAD

**Issue by mikecarrington** [stackpath/terraform-provider-stackpath#6]
### Terraform Version

Terraform version: 0.12.7

### Affected Resource(s)

* stackpath_0.1.0 provider (master branch)

### Terraform Configuration Files

```hcl
# Using app.terraform.io backend:
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "example"

    workspaces {
      name = "stackpath-dev"
    }
  }
}

provider "stackpath" {
  version = "~> 0.1"
  stack = var.stackpath_stack_id
  client_id = var.stackpath_client_id
  client_secret = var.stackpath_client_secret
}
```

### Debug Output

Gist showing output of 'init' and 'plan'
https://gist.github.com/mikecarrington/1e37e62f0d0bdc0c09fd9a26921ddc08

### Expected Behavior

Terraform plan should have run without any errors, the main.tf code connects to backend and loads the stackpath provider.

### Actual Behavior

Error: Could not satisfy plugin requirements
Error: provider.stackpath: no suitable version installed
  version requirements: "~> 0.1"
  versions installed: none

### Steps to Reproduce

1. `mkdir -p stackpath/provider & cd stackpath/provider`
2. `git clone https://github.com/stackpath/terraform-provider-stackpath.git`
3. `go build`
4. `mkdir ~/.terraform.d/plugins/linux_amd64`
5. `mv terraform-provider-stackpath ~/.terraform.d/plugins/linux_amd64/terraform-provider-stackpath_v0.1.0`
6. cd to your project folder
7. `terraform init`
8. `terraform plan`

### Important Factoids

Note: step 5 - the README.md suggests naming -v0.1.0 however that does not work. Boiler plate content has been copied from the default terraform provider README, needs updating to be Stackpath specific.

Enabling debug `export TF_LOG=debug` and running `terraform init` you can see a valid plugin is found;
`2019/08/27 21:36:24 [DEBUG] found valid plugin: "stackpath", "0.1.0", "/home/<username>/.terraform.d/plugins/linux_amd64/terraform-provider-stackpath_v0.1.0"`

Removing the version check in the main.tf does not work either.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mikecarrington** [comment]
Hi - tried with 0.3.0 no joy. Tried the release version locally rather then building and that has same issue. Tried putting directly in to project folder /terraform.d/... same issue, fine on `init` not so on `plan`.
Have just tried the darwin_amd64 v0.3.0 release on a mac and that worked ok. Also just tried the linux_amd64 release version on docker alpine:latest and that also worked.
Seems to point at either a local issue on machine / build of fedora. Will continue hunting, thanks.

**Comment by klaude** [comment]
@mikecarrington, I'm going to close this issue out early next week if we haven't heard back for you. Please let us know if there's anything we can do to help. Thanks!

**Comment by klaude** [comment]
I'm going to close this issue. Please open another if this persists or if there's anything else we can do for you. Thanks!
